name: BUG 提交
description: 插件不正常的情况
title: '[Bug]'
label:
  - bug
assignees: ltxhhz
body:
  - type: markdown
    attributes:
      value: |
        **提交 issue 前请先[搜索查看其他 issue](https://github.com/ltxhhz/LL-plugin-list-viewer/issues)，避免重复提交**
  - type: markdown
    attributes:
      value: |
        ## 环境信息
  - type: input
    id: qq-version
    validations:
       required: true
    attributes:
      label: QQNT 版本
      description: 在设置中LiteLoader分页里查看
  - type: input
    id: ll-version
    validations:
       required: true
    attributes:
      label: LiteLoader 版本
      description: 在设置中LiteLoader分页里查看
  - type: checkboxes
    id: LL-is-Dev
    attributes:
      label: LiteLoader 是否为开发版
      description: LiteLoader是否通过`git clone`下载安装,发行版(Release)请勿勾选
  - type: textarea
    id: versions
    attributes:
      label: 版本信息
      description: 把设置中LiteLoader分页里最上方的版本信息截图粘贴到这里
    validations:
       required: true
  - type: input
    id: version
    validations:
      required: true
    attributes:
      label: list-viewer 插件版本
      description: 在设置中LiteLoader分页里查看
  - type: input
    id: platform
    validations:
      required: true
    attributes:
      label: 使用平台
      description: 系统和版本
  - type: markdown
    attributes:
      value: "## 详细信息"
  - type: textarea
    id: what-happened
    attributes:
      label: 问题描述
      description: 简要描述您碰到的问题
    validations:
      required: true
  - type: textarea
    id: how-happened
    attributes:
      label: 重现步骤
      description: 如果操作可以重现该问题
    validations:
      required: true
  - type: textarea
    id: expect
    attributes:
      label: 期待的正确结果
  - type: textarea
    id: logs
    attributes:
      label: 相关日志输出
      description: |
        请复制并粘贴任何相关的日志输出（如果你会打开控制台或终端）<br>
        这将自动格式化为代码，因此无需反引号
      render: shell
  - type: textarea
    id: additional-information
    attributes:
      label: 附加信息
      description: 如果你还有其他需要提供的信息，可以在这里填写（截图、视频等）
