name: 功能请求
description: 请求开发者增加功能。
title: "[Feat]: "
labels: ["enhancement"]
assignees:
  - ltxhhz
body:
  - type: markdown
    attributes:
      value: |
        # 感谢您愿意花费时间来提出issue。
        我们很高兴您能为本插件提供您宝贵的想法与意见。
  - type: markdown
    attributes:
      value: |
        ## 在此之前,请您确认:
        - 没有相同的issue已被提出。
        - 您会准确、真实的填写下方内容。
        - 您了解[提问的智慧](https://github.com/tvvocold/How-To-Ask-Questions-The-Smart-Way)所讲述的内容。
  - type: checkboxes
    attributes:
      label: 请确保您已阅读以上注意事项，并勾选下方的确认框。
      options:
        - label: 我已经在[Issue Tracker](https://github.com/ltxhhz/LL-plugin-list-viewer/issues)中找过我要提出的功能请求，没有找到相同请求的issue。
          required: true
        - label: 我已知晓,如果我不真实填写issue,则我的issue可能会被无条件关闭&锁定&删除。
          required: true
  - type: textarea
    attributes:
      label: 请求增加的功能
      description: 请描述的详细一点,以便开发者快速理解。
    validations:
      required: true
  - type: textarea
    attributes:
      label: 功能实现的解决方案
      description: 请描述的详细一点,以便开发者快速理解。
    validations:
      required: false
  - type: textarea
    id: other
    attributes:
      label: 其它信息
    validations:
      required: false
