name: 功能请求
description: 请求开发者增加功能。
title: "[Feat]: "
labels: ["enhancement"]
assignees:
  - ltxhhz
body:
  - type: markdown
    attributes:
      value: |
        # 感谢您愿意花费时间来提出issue。
        我们很高兴您能为本插件提供您宝贵的想法与意见。
  - type: markdown
    attributes:
      value: |
        ## 在此之前,请您确认:
        - 没有相同的issue已被提出。
        - 您会准确、真实的填写下方内容。
  - type: checkboxes
    attributes:
      label: 请确保您已阅读以上注意事项，并勾选下方的确认框。
      options:
        - label: 我已经在[Issue Tracker](https://github.com/ltxhhz/LL-plugin-list-viewer/issues)中找过我要提出的功能请求，没有找到相同请求的issue。
          required: true
        - label: 我已知晓,如果我不真实填写issue,则我的issue可能会被无条件关闭&锁定&删除。
          required: true
  - type: input
    attributes:
      label: QQNT版本
      description: 左下角菜单中关于选项中的版本/LiteLoader分页中的QQNT版本。
      placeholder: 9.9.x-xxxxx
    validations:
      required: true
  - type: input
    attributes:
      label: LiteLoader版本
      description: LiteLoader分页中的LiteLoader版本。
      placeholder: 1.x.x
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: LiteLoader是否为开发版本
      description: LiteLoader是否是通过`git clone`命令下载安装的?如果不是,请勿勾选。
  - type: textarea
    attributes:
      label: Electron&Chromium&Node.js版本
      description: LiteLoader分页中的版本。<br>为了方便,请直接贴版本截图。
    options:
       - label: 这是开发版本
    validations:
      required: true
  - type: input
    attributes:
      label: 本插件版本
      description: list-viewer插件分页中的插件版本。
      placeholder: 1.x.x
    validations:
      required: true
  - type: textarea
    attributes:
      label: 请求增加的功能
      description: 请描述的详细一点,以便开发者快速理解。
    validations:
      required: true
  - type: textarea
    attributes:
      label: 功能实现的解决方案
      description: 请描述的详细一点,以便开发者快速理解。
    validations:
      required: false
  - type: textarea
    id: other
    attributes:
      label: 其它信息
    validations:
      required: false
